openapi: 3.1.0
info:
  title: QTSurfer API
  summary: QTSurfer backend services API
  version: 0.10.24
  license:
    name: Apache-2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'https://api.staging.qtsurfer.com'
    description: Staging server
  - url: 'https://api.qtsurfer.com'
    description: Production server
paths:
  '/exchanges':
    get:
      operationId: getExchanges
      summary: Get a list of available exchanges
      responses:
        '200':
          description: A JSON array of Exchanges
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exchange'
              example:
                - id: binance
                  name: Binance
                - id: kraken
                  name: Kraken
      security:
        - bearerAuth: []
      tags:
        - Exchange
  '/exchange/{exchangeId}/instruments':
    get:
      operationId: getInstruments
      summary: Get a list of Instruments from a specific exchange
      parameters:
        - name: exchangeId
          in: path
          description: ID of the exchange to retrieve instruments for
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A JSON array of Instruments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Instrument'
              example:
                - BTC/USDT
                - BTC/ETH
        '404':
          description: Exchange not found
      security:
        - bearerAuth: []
      tags:
        - Exchange
  '/strategy':
    post:
      operationId: postStrategy
      summary: Submits a strategy code to be compiled/validated
      requestBody:
        description: The strategy code to be submitted for validation
        required: true
        content:
          text/plain:
            schema:
              type: string
              description: The raw strategy code submitted by the user
      responses:
        '200':
          description: Strategy created/updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  strategyId:
                    $ref: '#/components/schemas/strategyId'
              example:
                strategyId: 6bsh31ikwkuivhtgcoa6s4
        '400':
          description: Invalid strategy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
              example:
                code: 400
                message: 'Line 1, Column 18: syntax error'
      security:
        - bearerAuth: []
      tags:
        - Strategy

components:
  schemas:
    ResponseError:
      description: General response error
      type: object
      properties:
        code:
          description: Status code
          type: integer
          example: 400
        message:
          description: Error description
          type: string
          example: Invalid request
    Instrument:
      description: Exchange instrument (eg. a currency pair)
      type: string
      example: BTC/USDT
    Exchange:
      description: Exchange service provider
      type: object
      properties:
        id:
          description: Unique identifier for the exchange
          type: string
          example: binance
        name:
          description: Name of the exchange
          type: string
          example: Binance
    strategyId:
      description: Unique identifier for a compiled strategy
      type: string
      example: 6bsh31ikwkuivhtgcoa6s4
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: Exchange
    description: |-
      This set of endpoints allows interaction with various **exchanges** for cryptocurrencies and financial assets. With these endpoints, users can access information about available exchanges, 
      retrieve the instruments (currency pairs or assets) offered by each exchange, and perform analyses on them. The data provided by these endpoints is crucial for strategic decision-making 
      within the trading platform.

      **Key functionalities**:
      - Retrieve the list of available exchanges on the platform.
      - Get the instruments available on a specific exchange (currency pairs, assets, etc.).
  - name: Backtesting
    description: |-
      The **backtesting** endpoints enable users to test trading strategies based on historical data before applying them in real-time trading. This functionality is essential for traders who want
      to evaluate the performance of a strategy under past market conditions and optimize it before implementing it in a live trading environment.

      **Key functionalities**:
      - Compile rich Java&trade; based strategies.
      - Run simulations of trading strategies using historical market data.
      - Assess performance and optimize strategies based on past results and metrics.
  - name: Strategy
    description: |-
      The **strategy** endpoints allow users to submit, compile, and validate trading strategies within the platform. This feature is crucial for traders who develop automated trading systems and
      wish to ensure their strategy is both executable and effective before deploying it in a live/backtesting environment.

      **Key functionalities**:
      - Submit trading strategies for validation and compilation.
      - Ensure strategies meet the required syntax and operational constraints.
      - Validate strategies to identify potential issues or errors before execution.
      - Integrate strategies with specific exchanges and market instruments for tailored use.
externalDocs:
  description: Find out more about QTSurfer API
  url: 'https://qtsurfer.com/developers'
security:
  - bearerAuth: []
