openapi: 3.1.0
info:
  title: QTSurfer API
  summary: QTSurfer backend services API
  version: 0.10.18
  license:
    name: Apache-2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

externalDocs:
  description: Find out more about QTSurfer API
  url: https://qtsurfer.com/developers

servers:
  - url: https://api-dev.qtsurfer.com
    description: Dev server
  - url: https://api.qtsurfer.com
    description: Production server

tags:
  - name: exchange
    description: Exchange
  - name: backtesting
    description: Backtesting

security:
  - bearerAuth: []

paths:
  /exchanges:
    get:
      tags:
        - exchange
      summary: Get a list of available exchanges
      operationId: getExchanges
      security:
        - bearerAuth: []
      responses:
        200:
          description: A JSON array of Exchanges
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Exchange"
              example:
                - id: binance
                  name: Binance
                - id: kraken
                  name: Kraken
  /exchange/{exchangeId}/instruments:
    get:
      tags:
        - exchange
      summary: Get a list of Instruments from a specific exchange
      operationId: getInstruments
      security:
        - bearerAuth: []
      parameters:
        - name: exchangeId
          in: path
          required: true
          description: ID of the exchange to retrieve instruments for
          schema:
            type: string
      responses:
        200:
          description: A JSON array of Instruments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Instrument"
              example: 
                - BTC/USDT
                - BTC/ETH
        404:
          description: Exchange not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Instrument:
      type: string
      description: Exchange instrument (eg. a currency pair)
      example: BTC/USDT
    Exchange:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the exchange
          example: binance
        name:
          type: string
          description: Name of the exchange
          example: Binance
