name: Generate Redoc HTML

on:
  push:
    paths:
      - "openapi.yaml"
    branches:
      - main

jobs:
  generate-redoc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install Redocly CLI
        run: |
          npm install -g @redocly/cli 

      - name: Generate HTML from OpenAPI
        run: |
          redocly build-docs openapi.yaml --output=index.html

      - name: Commit HTML file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: index.html
          commit_message: "chore: Updated OpenAPI HTML documentation"
